# Generated by Django 5.2.14 on 2026-09-07 01:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(("is_published", True)),
                fields=["-created_at"],
                name="post_published_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title", "body", config="english"
                ),
                name="post_fts_gin",
            ),
        ),
    ]
